In [60]:
from sklearn.linear_model import LinearRegression
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import math

In [4]:
df1=pd.read_csv(r"C:\Users\anoop\Downloads\case study\credit.csv")
df1

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0        20000.0    2          2         1   24      2      2     -1     -1   
1       120000.0    2          2         2   26     -1      2      0      0   
2        90000.0    2          2         2   34      0      0      0      0   
3        50000.0    2          2         1   37      0      0      0      0   
4        50000.0    1          2         1   57     -1      0     -1      0   
...          ...  ...        ...       ...  ...    ...    ...    ...    ...   
29995   220000.0    1          3         1   39      0      0      0      0   
29996   150000.0    1          3         2   43     -1     -1     -1     -1   
29997    30000.0    1          2         2   37      4      3      2     -1   
29998    80000.0    1          3         1   41      1     -1      0      0   
29999    50000.0    1          2         1   46      0      0      0      0   

       PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -2  ...        0.0        0.0        0.0       0.0     689.0   
1          0  ...     3272.0     3455.0     3261.0       0.0    1000.0   
2          0  ...    14331.0    14948.0    15549.0    1518.0    1500.0   
3          0  ...    28314.0    28959.0    29547.0    2000.0    2019.0   
4          0  ...    20940.0    19146.0    19131.0    2000.0   36681.0   
...      ...  ...        ...        ...        ...       ...       ...   
29995      0  ...    88004.0    31237.0    15980.0    8500.0   20000.0   
29996      0  ...     8979.0     5190.0        0.0    1837.0    3526.0   
29997      0  ...    20878.0    20582.0    19357.0       0.0       0.0   
29998      0  ...    52774.0    11855.0    48944.0   85900.0    3409.0   
29999      0  ...    36535.0    32428.0    15313.0    2078.0    1800.0   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default_payment_next_month  
0           0.0       0.0       0.0       0.0                           1  
1        1000.0    1000.0       0.0    2000.0                           1  
2        1000.0    1000.0    1000.0    5000.0                           0  
3        1200.0    1100.0    1069.0    1000.0                           0  
4       10000.0    9000.0     689.0     679.0                           0  
...         ...       ...       ...       ...                         ...  
29995    5003.0    3047.0    5000.0    1000.0                           0  
29996    8998.0     129.0       0.0       0.0                           0  
29997   22000.0    4200.0    2000.0    3100.0                           1  
29998    1178.0    1926.0   52964.0    1804.0                           1  
29999    1430.0    1000.0    1000.0    1000.0                           1  

[30000 rows x 24 columns]

In [16]:
df1.columns

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default_payment_next_month'],
      dtype='object')

In [19]:
x=df1.drop(["default_payment_next_month",'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6'],axis=1)
y=df1["default_payment_next_month"]

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [13]:
model=RandomForestClassifier()
model.fit(x_train,y_train)


RandomForestClassifier()

In [14]:
model.score(x_test,y_test)

0.818

In [15]:
cross_val_score(RandomForestClassifier(),x_train,y_train)

array([0.81833333, 0.82583333, 0.81645833, 0.81020833, 0.81375   ])

In [22]:
df1["MARRIAGE"].value_counts()

2    15964
1    13659
3      323
0       54
Name: MARRIAGE, dtype: int64

In [9]:
df=pd.read_csv(r"C:\Mba notes\novels\500_Person_Gender_Height_Weight_Index.csv")

In [10]:
df

Gender  Height  Weight  Bmi
0      Male     174      96    4
1      Male     189      87    2
2    Female     185     110    4
3    Female     195     104    3
4      Male     149      61    3
..      ...     ...     ...  ...
495  Female     150     153    5
496  Female     184     121    4
497  Female     141     136    5
498    Male     150      95    5
499    Male     173     131    5

[500 rows x 4 columns]

In [11]:
max(df["Height"]),max(df["Weight"]),max(df["Bmi"])

(199, 160, 5)

In [49]:
df1=df.copy()
df1["Height"]=df1["Height"]/199
df1["Weight"]=df1["Weight"]/160
df1["Bmi"]=df1["Bmi"]/5
df1.head(-1)

Gender    Height   Weight  Bmi
0      Male  0.874372  0.60000  0.8
1      Male  0.949749  0.54375  0.4
2    Female  0.929648  0.68750  0.8
3    Female  0.979899  0.65000  0.6
4      Male  0.748744  0.38125  0.6
..      ...       ...      ...  ...
494    Male  0.763819  0.61250  1.0
495  Female  0.753769  0.95625  1.0
496  Female  0.924623  0.75625  0.8
497  Female  0.708543  0.85000  1.0
498    Male  0.753769  0.59375  1.0

[499 rows x 4 columns]

In [50]:
max(df1["Height"]),max(df1["Weight"]),max(df1["Bmi"])

(1.0, 1.0, 1.0)

In [52]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df1[["Height","Weight"]],df1["Bmi"],test_size=0.2,random_state=10)

In [58]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation="sigmoid",kernel_initializer="ones",bias_initializer="zeros")
])
model.compile(optimizer="adam",
             loss="binary_crossentropy",
             metrics=["accuracy"])
model.fit(x_train,y_train,epochs=100)

Epoch 1/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5619 - accuracy: 0.3725
Epoch 2/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5600 - accuracy: 0.3725
Epoch 3/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5585 - accuracy: 0.3725
Epoch 4/100
13/13 [==============================] - 0s 1ms/step - loss: 0.5570 - accuracy: 0.3725
Epoch 5/100
13/13 [==============================] - 0s 1ms/step - loss: 0.5555 - accuracy: 0.3725
Epoch 6/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5543 - accuracy: 0.3725
Epoch 7/100
13/13 [==============================] - 0s 1ms/step - loss: 0.5531 - accuracy: 0.3725
Epoch 8/100
13/13 [==============================] - 0s 1ms/step - loss: 0.5520 - accuracy: 0.3725
Epoch 9/100
13/13 [==============================] - 0s 1ms/step - loss: 0.5510 - accuracy: 0.3725
Epoch 10/100
13/13 [==============================] - 0s 801us/step - loss: 0.5501 - accuracy: 0.3725
Epoch 1

Epoch 83/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5144 - accuracy: 0.3725
Epoch 84/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5140 - accuracy: 0.3725
Epoch 85/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5136 - accuracy: 0.3725
Epoch 86/100
13/13 [==============================] - ETA: 0s - loss: 0.5855 - accuracy: 0.28 - 0s 1ms/step - loss: 0.5132 - accuracy: 0.3725
Epoch 87/100
13/13 [==============================] - 0s 1ms/step - loss: 0.5129 - accuracy: 0.3725
Epoch 88/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5125 - accuracy: 0.3725
Epoch 89/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5121 - accuracy: 0.3725
Epoch 90/100
13/13 [==============================] - 0s 1ms/step - loss: 0.5117 - accuracy: 0.3725
Epoch 91/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5114 - accuracy: 0.3725
Epoch 92/100
13/13 [==============================] - 0s 1

In [59]:
model.evaluate(x_test,y_test)

4/4 [==============================] - 0s 2ms/step - loss: 0.4543 - accuracy: 0.4900


[0.4543198347091675, 0.49000000953674316]

In [70]:
coef,intercept=model.get_weights()
coef,intercept

(array([[0.3827794],
        [1.8776975]], dtype=float32),
 array([-0.43998075], dtype=float32))

In [87]:
print(model.predict(x_test),x_test)
y_predicted=model.predict(x_test)

[[0.6081549 ]
 [0.6291177 ]
 [0.76148105]
 [0.696093  ]
 [0.67726016]
 [0.8339763 ]
 [0.8211322 ]
 [0.8380914 ]
 [0.8533182 ]
 [0.72029454]
 [0.7866924 ]
 [0.6347578 ]
 [0.7673694 ]
 [0.7586037 ]
 [0.7254553 ]
 [0.80134964]
 [0.77807903]
 [0.77044547]
 [0.8183763 ]
 [0.7415478 ]
 [0.63702965]
 [0.8527628 ]
 [0.69175977]
 [0.8267685 ]
 [0.7974647 ]
 [0.6200978 ]
 [0.82135737]
 [0.7609546 ]
 [0.8303755 ]
 [0.8424796 ]
 [0.8085997 ]
 [0.69897485]
 [0.7831863 ]
 [0.7677126 ]
 [0.85489905]
 [0.7472594 ]
 [0.7875    ]
 [0.63328344]
 [0.6837446 ]
 [0.66687214]
 [0.678058  ]
 [0.6368947 ]
 [0.7363532 ]
 [0.7759446 ]
 [0.6631022 ]
 [0.7385877 ]
 [0.7605337 ]
 [0.8530286 ]
 [0.8493245 ]
 [0.7238079 ]
 [0.8279786 ]
 [0.76450604]
 [0.74758583]
 [0.826465  ]
 [0.7052083 ]
 [0.8433467 ]
 [0.85570955]
 [0.7611315 ]
 [0.7893603 ]
 [0.7599034 ]
 [0.84405637]
 [0.683539  ]
 [0.744745  ]
 [0.7065679 ]
 [0.8439027 ]
 [0.7584612 ]
 [0.7610254 ]
 [0.61537194]
 [0.7109355 ]
 [0.71271324]
 [0.82972616]
 [0.80

In [64]:
def sigmoid(x):
    return 1/(1+math.exp(-x))

In [68]:
sigmoid(18)

0.9999999847700205

In [76]:
def prediction_function(Height,Weight):
    weighted_sum=coef[0]*Height+coef[1]*Weight+intercept
    return sigmoid(weighted_sum)

In [77]:
prediction_function(0.703518,0.32500)

0.6081549202439401

In [90]:
y_predicted=[1,1,0,0,1]

In [95]:
eplison=1e-15
y_predicted_new=[max(i,eplison) for i in y_predicted]
y_predicted_new=[min(i,1-eplison) for i in y_predicted_new]
y_predicted_new=np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [112]:
raw_data={
    "Age":[23,45,78,43,27,34,65,43,66,32,37,83,29],
    "Affordability":[1,0,1,0,0,1,1,1,1,0,1,1,0],
    "Bought":[0,0,1,0,0,0,1,1,1,0,0,1,0]
}
df1=pd.DataFrame(raw_data,index=None)
x_train,y_train

(   Age  Affordability
 7   43              1
 8   66              1
 3   43              0
 0   23              1
 4   27              0
 6   65              1
 5   34              1
 9   32              0
 1   45              0,
     Age  Affordability
 12   29              0
 2    78              1
 10   37              1
 11   83              1)

In [115]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df1[["Age","Affordability"]],df1["Bought"],test_size=0.3,random_state=28)
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation="sigmoid",kernel_initializer="ones",bias_initializer="zeros")
])
model.compile(optimizer="adam",
             loss="binary_crossentropy",
             metrics=["accuracy"])
model.fit(x_train,y_train,epochs=100)
y_pred=model.predict(y_test)

Epoch 1/100
1/1 [==============================] - 0s 0s/step - loss: 22.8889 - accuracy: 0.3333
Epoch 2/100
1/1 [==============================] - 0s 0s/step - loss: 22.8653 - accuracy: 0.3333
Epoch 3/100
1/1 [==============================] - 0s 3ms/step - loss: 22.8418 - accuracy: 0.3333
Epoch 4/100
1/1 [==============================] - 0s 3ms/step - loss: 22.8182 - accuracy: 0.3333
Epoch 5/100
1/1 [==============================] - 0s 998us/step - loss: 22.7947 - accuracy: 0.3333
Epoch 6/100
1/1 [==============================] - 0s 3ms/step - loss: 22.7711 - accuracy: 0.3333
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: 22.7476 - accuracy: 0.3333
Epoch 8/100
1/1 [==============================] - 0s 1ms/step - loss: 22.7240 - accuracy: 0.3333
Epoch 9/100
1/1 [==============================] - 0s 0s/step - loss: 22.7004 - accuracy: 0.3333
Epoch 10/100
1/1 [==============================] - 0s 996us/step - loss: 22.6769 - accuracy: 0.3333
Epoch 11/100
1/1 [

ValueError: in user code:

    C:\Mba notes\novels\Anaconda\lib\site-packages\tensorflow\python\keras\engine\training.py:1462 predict_function  *
        return step_function(self, iterator)
    C:\Mba notes\novels\Anaconda\lib\site-packages\tensorflow\python\keras\engine\training.py:1452 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Mba notes\novels\Anaconda\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Mba notes\novels\Anaconda\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Mba notes\novels\Anaconda\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Mba notes\novels\Anaconda\lib\site-packages\tensorflow\python\keras\engine\training.py:1445 run_step  **
        outputs = model.predict_step(data)
    C:\Mba notes\novels\Anaconda\lib\site-packages\tensorflow\python\keras\engine\training.py:1418 predict_step
        return self(x, training=False)
    C:\Mba notes\novels\Anaconda\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:975 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs,
    C:\Mba notes\novels\Anaconda\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:212 assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer sequential_25 is incompatible with the layer: expected axis -1 of input shape to have value 2 but received input with shape [None, 1]


In [122]:
y_pred=model.predict(x_test)
weights,intercept=model.get_weights()
weights,intercept

(array([[0.9000013],
        [0.9000013]], dtype=float32),
 array([-0.09999996], dtype=float32))

In [125]:
x_test,y_pred

(    Age  Affordability
 12   29              0
 2    78              1
 10   37              1
 11   83              1,
 array([[1.],
        [1.],
        [1.],
        [1.]], dtype=float32))

In [124]:
def sigmoid(y):
    return np.array(1/(1+math.exp(-y)))
sigmoid(18)

array(0.99999998)

In [128]:
def prediction_function(Age,Affordability):
    weighted_sum=weights[0]*Age+weights[1]*Affordability+intercept
    return sigmoid(weighted_sum)
prediction_function(2,78)    

array(1.)

In [97]:
#log_loss=-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [168]:
def log_loss(y_true,y_predicted):
    eplison=1e-10
    y_predicted_new=[max(i,eplison) for i in y_predicted]
    y_predicted_new=[min(i,1-eplison) for i in y_predicted_new]
    y_new=np.array(y_predicted_new)
    loss=-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))
    
   


In [169]:
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))

In [170]:
def gradient_descent(age,affordability,y_true,epochs):
    w1=w2=1
    bias=0
    rate=0.5
    n=len(age)
    
    for i in range(epochs):
        weighted_sum=w1*age + w2*affordability + bias
        y_predicted=sigmoid_numpy(weighted_sum)
        loss=log_loss(y_true,y_predicted)
        
        w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d=(1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))
                         
        bias_d=np.mean(y_predicted-y_true)
                         
        w1=w1-rate*w1d
        w2=w2-rate*w2d
        bias=bias-rate*bias_d
                         
        print(f"Epoch:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}")
              
    return w1,w2,bias
        

In [171]:
gradient_descent(x_train["Age"],x_train["Affordability"],y_train,100)

TypeError: unsupported operand type(s) for -: 'int' and 'list'

In [149]:
y_train

7    1
8    1
3    0
0    0
4    0
6    1
5    0
9    0
1    0
Name: Bought, dtype: int64

In [1]:
import random

In [2]:
a=[i for i in range(1,31)]

In [14]:
random.sample(a,6)

[22, 23, 7, 9, 25, 5]

In [12]:
random.choice(a)

27

In [7]:
x=input("Enter Number 1 ")
y=input("Enter Number 2 ")
try:
    z=int(x)/int(y)
except Exception as e:
    print("exception occured : ",e)
    z=None
print("Division is : ",z)

Enter Number 1 4
Enter Number 2 2
Division is :  2.0


In [6]:
x=input("Enter Number 1 ")
y=input("Enter Number 2 ")
try:
    z=x/y
except ZeroDivisionError as e:
    print("Division by zero exception : ",e)
    z="Not Defined"
except TypeError as e:
    print("exception type: ",type(e).__name__)
    z=None
print("Division is : ",z)

Enter Number 1 3
Enter Number 2 2
exception type:  TypeError
Division is :  None


In [5]:
x=input("Enter Number 1 ")
y=input("Enter Number 2 ")
try:
    z=x/y
except ZeroDivisionError as e:
    print("Division by zero exception : ",e)
    z="Not Defined"
except TypeError as e:
    print("TypeError")
    z=None
print("Division is : ",z)

Enter Number 1 3
Enter Number 2 2
TypeError
Division is :  None


In [14]:
x=input("1st number ")
y=input("2nd number ")
try:
    z=int(x)/int(y)
except TypeError as e:
    print("TypeError")
    z=None
except ValueError as e:
    print("ValueError")
    z=None
print("division is ",z)

1st number r
2nd number 3
ValueError
division is  None


In [16]:
try:
    raise MemoryError("memory error")
except MemoryError as e:
    print(e)

memory error


In [19]:
class Accident(Exception):
    def __init__(self,msg):
        self.msg=msg
        
    def print_exception(self):
        print("User defined exception : ",self.msg)
        
try:
    raise Accident("Crash between two cars")
except Accident as e:
    e.print_exception()

User defined exception :  Crash between two cars


In [23]:
class Error(Exception):
    def __init__(self,msg):
        self.msg=msg
        
    def exception(self):
        print("Ashish defined error : ",self.msg)
    
try:
    raise Error("M hu error ki duniya ka don")
except Error as e:
    e.exception()

Ashish defined error :  M hu error ki duniya ka don


In [50]:
def process_file():
    try:
        f=open("C:/Mba notes/novels/adult")
        z=1/0
    except FileNotFoundError as e:
        print("inside exception")
    finally:
        print("cleaning up file")
        f.close()
process_file()

inside exception
cleaning up file


UnboundLocalError: local variable 'f' referenced before assignment

In [22]:
class Error():
    try:
        def __init__(self,number):
            self.x=1
            self.y=6
            self.number=number
        def fact(self):
            for i in range(1,self.number+1):
                self.x=i*self.x
            return self.x
    except Exception as e:
        print("Exception Type : ",type(e).__name__)
            

In [23]:
obj=Error(5)
obj.fact()

120

In [55]:
class Error(Exception):
        
    try:
        def __init__(self,number):
            try:
                self.error=error
                self.x=0
                self.y=6
            except Exception as e:
                print("Exception Type : ",type(e).__name__)
            finally:
                print("Yes")
                
        def fact(self):
            try:
                for i in range(1,len(number)+1):
                    self.x=number[i]*self.x
                return self.x
            except Exception as e:
                print("Exception Type : ",type(e).__name__)
    finally:
        print("Yes")
    

Yes


In [56]:
obj=Error(6)

Exception Type :  NameError
Yes


In [57]:
108*2

216

In [58]:
200*2

400