In [1]:
import math
import random
import array as ar
import pandas as pd
from array import *
import numpy as np
import cv2

In [6]:
data={
    "name":["red","green","orange"],
    "number":[1,2,3]
}
pd.DataFrame(data)

name  number
0     red       1
1   green       2
2  orange       3

In [14]:
number=[1,2,3,4,5]
letter=["a","b","c","d","e"]
pd.DataFrame([number,letter])

0  1  2  3  4
0  1  2  3  4  5
1  a  b  c  d  e

In [3]:
def ashish(a,b="Ashish "):
    print(b+a+" chhetri")


In [4]:
ashish("kumar")

Ashish kumar chhetri


In [5]:
def math(a,b):
    return a*b
    

In [6]:
math(2,3)

6

In [7]:
math(8,9)

72

In [20]:
a=[2,3,1,5,3,7,6]
b=[4,5,8,6,9,6,5,0]

In [12]:
math.pow(3,4)

81.0

In [24]:
c=math.sqrt(4)
c=int(c)
c


2

In [31]:
random.randint(0,9)

3

In [37]:
d="Hello World"
print(d[1],d[6],d[0],d[-1],d[-4],d[-1:-4])

e W H d o 


In [43]:
len(d)

11

In [44]:
print(d[])

Hello World


In [14]:
def max2nubers(numbers=4): 
    for i in range(numbers):
        a=input("Enter the number")
        f=[]
        b=f.append(i)
    try:
        d=max(f)
        c=f.index(max(f))
        a.pop(c)
        e=max(f)
        print(d,e)
    except:
        print("You have written an string")

In [15]:
max2nubers()

Enter the number34
Enter the number55
Enter the number83
Enter the number48
You have written an string


In [46]:
def ab(number=5):
    b=[]
    for i in range(number):   
        a=int(input("Numbers"))
        b.append(a)
    c=max(b)
    d=b.index(max(b))
    b.pop(d)
    e=max(b)
    print(c,e)


In [47]:
ab()

Numbers33
Numbers56
Numbers76
Numbers54
Numbers56
76 56


In [57]:
a=[1,2,3,45,4,7,7,7,4,3]
a.remove(max(a))
a

[1, 2, 3, 4, 7, 7, 7, 4, 3]

In [58]:
a.count(7)

3

In [66]:
b=[]
for i in range(5):
    b.append(i)
b

[0, 1, 2, 3, 4]

In [69]:
b.insert(5,2)
b

[0, 1, 2, 3, 4, 2, 2]

In [13]:
b=[]
a="Ashish"
c=a.split()
for i in c:
    b.extend(i)
b

['A', 's', 'h', 'i', 's', 'h']

In [9]:
a.count('s')

2

In [19]:
a=["Banana","Apple","Orange","Juice"]
b=["Ant","Tiger"]
a.append(b)
a

['Banana', 'Apple', 'Orange', 'Juice', ['Ant', 'Tiger']]

In [20]:
a=["Banana","Apple","Orange","Juice"]
b=["Ant","Tiger"]
a.extend(b)
a

['Banana', 'Apple', 'Orange', 'Juice', 'Ant', 'Tiger']

In [21]:
a.index("Orange")

2

In [23]:
a.insert(2,"Grape")
a

['Banana', 'Apple', 'Grape', 'Grape', 'Orange', 'Juice', 'Ant', 'Tiger']

In [24]:
a.sort()
a

['Ant', 'Apple', 'Banana', 'Grape', 'Grape', 'Juice', 'Orange', 'Tiger']

In [ ]:
#list is orered- means that when we add an element to the list it will be added at the end of the list ,not in the between
#changable-means list items can be changed
#Allow Duplicates

In [59]:
a=[True,False,True]
len(a)

3

In [4]:
sample=ar.array("i",[1,2,3,4])
for i in sample:
    print(i)

1
2
3
4


In [34]:
sample=ar.array("i",[1,2,3,4,5,6,7,8,9,10])
for i in sample:
    print(i)
    

1
2
3
4
5
6
7
8
9
10


In [66]:
a=[1,2,3,4]
np.mean(a)

2.5

In [73]:
x=3
y=2
z=[]
while (x<101):
    while (y<int((x+1)/2)):
        if x%y==0:
            break
        y=y+1
    else:
        z.append(x)
    x=x+1
print(z)

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [26]:
for a in range(2,30):
    for i in range(1,30):
        pass
    if a%5==0:
        continue
    if a%7==0:
        break


29
29
29


# Printing of Table

In [2]:
a=int(input("Enter the number for which you want to print table"))
for i in range(1,11):
    print(a," X ",i," = ",a*i)

Enter the number for which you want to print table5
5  X  1  =  5
5  X  2  =  10
5  X  3  =  15
5  X  4  =  20
5  X  5  =  25
5  X  6  =  30
5  X  7  =  35
5  X  8  =  40
5  X  9  =  45
5  X  10  =  50


In [36]:
a=int(input("enter how many number you want to enter"))
c=[]
for i in range(a):
    b=int(input("Enter the number"))
    c.append(b)
print("max is ",max(c),"min is ",min(c))

enter how many number you want to enter3
Enter the number23
Enter the number23
Enter the number45
max is  45 min is  23


In [12]:
a=int(input("Print upto how much number you want to add prime number "))
b=0
for i in range(2,a+1):
    c=2
    for j in range(2,i):
        if a%j==0:
            break
    if i!=j:
        b+=i
print(b)

KeyboardInterrupt: Interrupted by user

In [16]:
a=1
for i in range(1,5):
    b=a+i
    a,i=i,b
print(b)
    
    

9


# Program to check if a small string can be made of bigger string

In [52]:
a="Ashish"
c="shas"
b=[]
for i in a:
    b.append(i.lower())
d=[]
e=[]
for i in c:
    d.append(i.lower())
d=set(d)
d=list(d)
print(d)
for i in d:
    for j in b:
        if i==j:
            e.append(i)
e=set(e)
e=list(e)
print(e)
if e==d:
    print("Yes")
else:
    print("No")

        

['s', 'h', 'a']
['s', 'h', 'a']
Yes


# Prime Number

In [30]:
num=int(input("Enter the number "))
for i in range(2,int(num/2)):
    if num%i==0:
        print("Not Prime")
        break
else:
    print("Prime")
                

            

Enter the number 10
Not Prime


In [56]:
a=int(input("Enter rthe number "))
b=0
for i in range(2,a+1):
    c=2
    for j in range(2,i):
        if (i%j==0):
            c=i
            break
    if c!=i:
        b+=i
print(b+2)
                
        

Enter rthe number 20
77


In [55]:
a=int(input("ENter The Number"))
b=[]
for i in range(3,a+1):
    for j in range(2,i):
        if i%j==0:
            break
    else:
        b.append(i)
Sum=sum(b)+2
print(Sum)             

ENter The Number20
77


# Pallendrome

In [7]:
a=input("object :")
a=list(a)
b=list(reversed(a))
if a==b:
    print("Pallendrome")
else:
    print("Not Pallendrome")


object :abba
['a', 'b', 'b', 'a']
['a', 'b', 'b', 'a']
Pallendrome


In [9]:
a=[]
c=int(input("Enter last range number"))
for i in range(3,c):
    for j in range(2,i):
        if i%j==0:
            break
    else:
        a.append(i)
print(sum(a)+2)

Enter last range number19
58


# Classes and Objects

In [8]:
class Human:
    def __init__(self,n,o):
        self.name=n
        self.occupation=o
        
    def do_work(self):
        if self.occupation=="tennis player":
            print(self.name,"plays tennis")
        elif self.occupation=="actor":
            print(self.name,"do acting")
            
    def speaks(self):
        print(self.name,"says how are you ?")
    

In [9]:
Ashish=Human("Ashish","actor")
Ashish.do_work()
Ashish.speaks()

Ashish do acting
Ashish says how are you ?


In [31]:
class Calculator:
    
    def __init__(self,n1,n2,operation):
        self.operation=operation
        self.n1=n1
        self.n2=n2
    
    def multiplication(self):
        if self.operation=="multiply":
            print(n1*n2)

In [1]:
a=Calculator(3,4,"multiply")
a.multiplication()

NameError: name 'Calculator' is not defined

# Fabinacco Series

In [164]:
num=int(input("Enter the number"))
a=0
b=1
for i in range(2,num):
    c=a+b
    a,b=b,c
    print(c)

Enter the number10
1
2
3
5
8
13
21
34


# Factorial

In [5]:
a=int(input("Enter the Number"))
b=1
for i in range(2,a+1):
    b=i*b
print(b)


Enter the Number5
120


In [4]:
num=int(input("Enter the Number "))
fac=1
i=1
while i<=num:
    fac=fac*i
    i=i+1
print(fac)
    
    

Enter the Number 6
720


# Program for Simple Interest and compound Interest

In [7]:
p=int(input("Enter Principal amount "))
r=int(input("Rate "))
t=int(input("Enter Time "))
def SI(p,r,t):
    si=(p*r*t)/100
    return si
SI(10,10,10)

Enter Principal amount 10
Rate 10
Enter Time 10


10.0

In [14]:
def CI(p,r,t,n):
    a=p*((1+r/n)**n*t)
    return a

In [16]:
 CI(10,10,1,2)

360.0

In [14]:
10**2

100

# Program to reverse an Integer and string

In [21]:
a="Ashish"
b=[1,2,3,4]
c=int()
for i in b:
    c=c+i*(10**(len(b)-i))
    print(c,i)
c

1000 1
1200 2
1230 3
1234 4


1234

In [53]:
string="Hello"
reverse=list(reversed(string))
reverse="".join(reverse)
reverse

'olleH'

In [69]:
s="Hello"
reverse=""
for i in range(len(s)):
    reverse+=s[len(s)-i-1]
reverse

'olleH'

In [27]:
def reverse(integer):
    reverse=int(integer[::-1])
    return reverse
\
reverse("1234")

4321

# Multiplying 2 list 

In [31]:
a=[1,2,3,4]
b=[5,6,7,8]
for i,j in enumerate(a):
    c=j*b[i]
    print(c)

5
12
21
32


In [33]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]
tmp=1
for i,j in zip(a,b):
    print(i*j)
    
    
        
        

6
14
24
36
50


In [36]:
products=[i*j for i,j in zip(a,b)]
products

[6, 14, 24, 36, 50]

In [37]:
for i in range(len(a)):
    print(a[i]*b[i])

6
14
24
36
50


# Armstrong Number

In [65]:
a=input("Enter the Number ")
b=[]
for i in range(len(a)):
    b.append(int(a[i])**3)
if sum(b)==int(a):
    print("number is Armstrong")
else:
    print("Number is not Armstrong")

Enter the Number 371
number is Armstrong 371 371


In [66]:
 7**3+3**3+1

371

# Numpy

3 Main benefits of numpy over list                                    
1.Less Memory                                                         
2.Fast                                                 
3.Convinient                                      

In [1]:
import numpy as np
import time 
import sys

In [8]:
l=range(1000)
print("Size is ",sys.getsizeof(5)*len(l))

Size is  28000


In [9]:
array=np.arange(1000)
print("Size is ",array.size*array.itemsize)

Size is  4000


In [20]:
SIZE=1000000
l1=range(SIZE)
l2=range(SIZE)

In [21]:
a1=np.arange(SIZE)
a2=np.arange(SIZE)

In [26]:
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
end=time.time()
print("list take ",(end-start)*1000)

list take  260.5416774749756


In [27]:
start=time.time()
result=a1+a2
end=time.time()
print("numpy took ",(end-start)*1000)

numpy took  20.303010940551758


In [69]:
 a=np.array([[1,2,3],[2,3,4],[3,4,5]])

In [70]:
a[0][2]

3

In [72]:
a[2][1]

4

In [73]:
a.ndim

2

In [78]:
print("print the bytesize is",a.itemsize)
a.dtype

print the bytesize is 4


dtype('int32')

In [80]:
b=np.array([[1,2],[2,3],[4,5]],dtype=np.float64)
b.itemsize

8

In [81]:
b

array([[1., 2.],
       [2., 3.],
       [4., 5.]])

In [88]:
print(f"size of b is {b.size} .  ",f"size of a is {a.size}")

size of b is 6 .   size of a is 9


In [89]:
b.shape

(3, 2)

In [90]:
a.shape

(3, 3)

In [94]:
b=np.array([[1,2],[2,3],[4,5]],dtype=complex)
b.itemsize

16

In [95]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [96]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [97]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [102]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [106]:
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
a.shape

(3, 3)

In [107]:
a.ravel()

array([1, 2, 3, 3, 4, 5, 4, 5, 6])

In [108]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [109]:
a.sum(axis=0)

array([ 8, 11, 14])

In [110]:
a.sum(axis=1)

array([ 6, 12, 15])

In [111]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [112]:
a[0:2,2]

array([8, 3])

In [113]:
a[-1]

array([9, 3, 2])

a[ rows , columns ]

In [116]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [120]:
a[1:3,:]

array([[1, 2, 3],
       [9, 3, 2]])

In [121]:
a[:,:]

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [122]:
for i in a.flat:
    print(i)

6
7
8
1
2
3
9
3
2


In [129]:
a=np.array([[1,2,3],[2,3,4],[3,4,5]],dtype="int32")
a.dtype

dtype('int32')

In [130]:
b=np.array([[4,5,6],[5,6,7],[6,7,8]],dtype="int32")
b.dtype

dtype('int32')

In [132]:
c=np.array([[7,8,9],[8,9,10],[10,11,12]],dtype="float")
c.dtype

dtype('float64')

In [134]:
a_b=np.vstack((a,b))
a_b

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

In [135]:
a_c=np.vstack((a,c))
a_c

array([[ 1.,  2.,  3.],
       [ 2.,  3.,  4.],
       [ 3.,  4.,  5.],
       [ 7.,  8.,  9.],
       [ 8.,  9., 10.],
       [10., 11., 12.]])

In [136]:
a_c.dtype

dtype('float64')

In [138]:
np.hstack((a,b)).dtype


dtype('int32')

In [142]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [146]:
result=np.hsplit(a,3)

In [147]:
print(result[1],result[0],result[2])

[[ 5  6  7  8  9]
 [20 21 22 23 24]] [[ 0  1  2  3  4]
 [15 16 17 18 19]] [[10 11 12 13 14]
 [25 26 27 28 29]]


In [148]:
result=np.vsplit(a,2)

In [149]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [150]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [151]:
c=a>4
c

array([[False, False, False, False, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True]])

In [157]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [158]:
for i in a.flatten():
    print(i)

0
1
2
3
4
5


In [159]:
for i in np.nditer(a,order="C"):
    print(i)

0
1
2
3
4
5


In [160]:
 for i in np.nditer(a,order="F"):
    print(i)

0
2
4
1
3
5


# Sum of square of natural numbers

In [8]:
num=int(input("Enter rhe number"))
a=[]
for i in range(1,num+1):
    a.append(i*i)
    print(a)
sum(a)

Enter rhe number4
[1]
[1, 4]
[1, 4, 9]
[1, 4, 9, 16]


30

In [11]:
num=int(input("Enter rhe number"))
a=[]
b=0
for i in range(1,num+1):
    a=i*i
    b=b+a
print(b)

Enter rhe number4
30


# Find greatest and smallest number in array


In [39]:
a=[3,2,5,6,7,5,8,9,5]
for i in a:
    for j in a:
        if i<j:
            break
    else:
        print("Max is ",i)
         

Max is  9


In [40]:
for i in a:
    for j in a:
        if i>j:
            break
    else:
        print("Min is ",i)

Min is  2


In [1]:
a=[1,2,3,4,5,6,7,8]
a[0]+a[-1]

9

# Find remainder of array multiplication divided by n

In [7]:
a=[2,3,4,5,6,4,3,2]
b=1
for i in a:
    b=b*i
print(b,len(a))
print(b%len(a))

17280 8
0


In [8]:
17280/8 

2160.0

# Program to find an array is monotonic or not

In [26]:
a=[1,2,4,7,9]
b=[]
for i in a:
    if a[-1]>=i:
        b.append("monotonic")
    else:
        b.append("Not monotonic")
        break
print(b[-1])

monotonic


In [3]:
a=[1,2,7,7,9]
b=[]
for i in range(len(a)-1):
    if a[-1]>a[i]:
        b.append("Monotonic")
    elif 
    else:
        b.append("Not Monotonic")
        break
print(b[-1])

Monotonic


In [7]:
a=[1,2,3,4,3,2,4,5,3]
for i in range(len(a)):
    for j in a:
        if a[i]==j:
            print(a[i],"duplicate")
        else:
            print(a[i],"not duplicate")

1 duplicate
1 not duplicate
1 not duplicate
1 not duplicate
1 not duplicate
1 not duplicate
1 not duplicate
1 not duplicate
1 not duplicate
2 not duplicate
2 duplicate
2 not duplicate
2 not duplicate
2 not duplicate
2 duplicate
2 not duplicate
2 not duplicate
2 not duplicate
3 not duplicate
3 not duplicate
3 duplicate
3 not duplicate
3 duplicate
3 not duplicate
3 not duplicate
3 not duplicate
3 duplicate
4 not duplicate
4 not duplicate
4 not duplicate
4 duplicate
4 not duplicate
4 not duplicate
4 duplicate
4 not duplicate
4 not duplicate
3 not duplicate
3 not duplicate
3 duplicate
3 not duplicate
3 duplicate
3 not duplicate
3 not duplicate
3 not duplicate
3 duplicate
2 not duplicate
2 duplicate
2 not duplicate
2 not duplicate
2 not duplicate
2 duplicate
2 not duplicate
2 not duplicate
2 not duplicate
4 not duplicate
4 not duplicate
4 not duplicate
4 duplicate
4 not duplicate
4 not duplicate
4 duplicate
4 not duplicate
4 not duplicate
5 not duplicate
5 not duplicate
5 not duplicate
5 no

In [40]:
def isMonotonic(A):
    return (all(a[i])<=A[i+1] for i in range(len(a)-1)) or
    all(a[i]>=a[i+1] for i in range(len(a)-1))

SyntaxError: invalid syntax (<ipython-input-40-b23e602b9b0e>, line 2)

In [ ]:
a=[1,2,3,4,5,6,7]


# Program to split a string

In [2]:
a=[12345]
output=list(map(int,str(a[0])))
print(output)

[1, 2, 3, 4, 5]


In [4]:
a=[3,2,4,3,4]
b=[int(x) if x.isdigit() else x for z in a for x in str(z)]
b

[3, 2, 4, 3, 4]

In [3]:
[int(i,16) for i in "1234"]

[1, 2, 3, 4]

In [5]:
a=12345
[int(i,16) for i in str(a)]

[1, 2, 3, 4, 5]

In [7]:
print("Hello "+"world")

Hello world


# Program for Duplicate

In [1]:
a=[1,2,3,4,3,2,4,5,6,7,6,5,4]
b=[]
c=[]
for i in range(len(a)):
    for j in range(i+1,len(a)):
        if a[i]==a[j]:
            b.append(a[i])
print("Duplicates are", set(b))

Duplicates are {2, 3, 4, 5, 6}


In [4]:
for i in range(len(a)):
    for j in range(i+1,len(a)):
        if a[i]==a[j]:
            print(a[i],"is a duplicate")
            break

2 is a duplicate
3 is a duplicate
4 is a duplicate
4 is a duplicate
5 is a duplicate
6 is a duplicate


# Just for Fun

In [79]:
while True:
    key=input()
    if key=="q":
        break

hello duniya
q


In [37]:
import math
dir(math)


['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [68]:
a=[2]
for i in range(3,100):
    for j in range(2,int((i/2)+1)):
        if i%j==0:
            break
    else:
        a.append(i)
a

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

In [6]:
class Ashish:
    def about_me(self):
        print("Hey this is about me,Ashish")
    
class Name(Ashish):
    def __init__(self,name):
        self.name=name
    
    def Name(self):
        if self.name=="Sister":
            print("Sakshi")
        if self.name=="Father":
            print("Mr.Prem")
        if self.name=="Mother":
            print("Mrs.Laxmi")
        
    
    

In [13]:
Ashish=Name("Mother")
Ashish.Name()

Mrs.Laxmi


In [16]:
Ashish.about_me()

Hey this is about me,Ashish


# Program to interchange last and first word in an element 

In [4]:
from collections import deque
a=[1,2,3,4,5]
b=a[-1]
c=a[1]
a.remove(1)
a.remove(len(a))

In [5]:
a

[2, 3, 5]

In [7]:
from collections import deque
a=deque()

In [10]:
a.append(1)
a.append(2)
a.append(3)
a.append(4)

In [11]:
a.appendleft(5)

In [12]:
a

deque([5, 1, 2, 3, 4])

In [24]:
def interchange(a):
    last=a.pop()
    first=a.pop(0)
    a.insert(0,last)
    a.insert(len(a),first)
    return a

In [26]:
interchange([3,4,5,6,4,3,2])

[2, 4, 5, 6, 4, 3, 3]

# To check if element exist in list or not

In [30]:
def number(List,number):
    for i in a:
        if i==number:
            print("Yes")
            break
    else:
        print("No")

In [31]:
number([1,2,3,4,5],7)

No


# Program to add 2 matrices

In [153]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [154]:
b=[[7,8,9],[4,5,6],[1,2,3]]
b

[[7, 8, 9], [4, 5, 6], [1, 2, 3]]

In [76]:
result=[]
r=[]
for i,j in zip(a,b):
    for k,l in zip(i,j):
        result.append(k+l)
print(result)
l=[[i for i in result[0:3]],[j for j in result[3:6]],[k for k in result[6:9]]]
l

[8, 10, 12, 8, 10, 12, 8, 10, 12]


[[8, 10, 12], [8, 10, 12], [8, 10, 12]]

In [72]:
result.__class__

list

In [80]:
import numpy as np
a=np.matrix(a)
b=np.matrix(b)
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [81]:
b

matrix([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]])

In [82]:
a+b

matrix([[ 8, 10, 12],
        [ 8, 10, 12],
        [ 8, 10, 12]])

In [83]:
a*b

matrix([[ 18,  24,  30],
        [ 54,  69,  84],
        [ 90, 114, 138]])

# Multiplication of 2 Matrix

In [155]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [156]:
b

[[7, 8, 9], [4, 5, 6], [1, 2, 3]]

In [160]:
len(a),len(b[0]),len(b)

(3, 3, 3)

In [161]:
result=[[0,0,0],
       [0,0,0],
       [0,0,0]]
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            result[i][j]+=a[i][k]*b[k][j]
            
# for 1st iteraton ,result[0][0]=a[0][0]*b[0][0] + a[0][1]*b[1][0] + a[0][2]b[2][1] 


In [18]:
result

[[18, 24, 30], [54, 69, 84], [90, 114, 138]]

In [52]:
result=[[sum(i*j for i,j in zip(x_row,y_col)) for y_col in zip(*b)] for x_row in a]
result

[[18, 24, 30], [54, 69, 84], [90, 114, 138]]

In [170]:
result=[[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            result[i][k]+=a[i][k]*b[k][j]
            

# Median

In [28]:
a=[1,2,3,4,5,6,7,5,4,3,4,5,6,7,2,1,3,2,3]
a.sort()
b=int(len(a)/2)
print(int(b),len(a),a)
median=a[b]
median

9 19 [1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7]


4

# Reverse

In [43]:
a=[1,2,3,4]

In [36]:
b=[]
for i in range(len(a)):
    b.append(a.pop())
b

[4, 3, 2, 1]

In [44]:
a=list(reversed(a))
a

[4, 3, 2, 1]

# TransPose Of an 2D array

In [167]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
result=[[0,0,0],
       [0,0,0],
       [0,0,0]]
for i in range(len(a)):
    for j in range(len(a[0])):
        result[j][i]=a[i][j]
        
for r in result:
    print(r)

[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [169]:
result=[[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(len(result)):
    for j in range(len(result[0])):
        result[i][j]=a[j][i]
for r in result:
    print(r)

[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [5]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [6]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [2]:
a=cv2.imread(r"C:\Users\anoop\Pictures\Screenshots\Screenshot (35).png")

In [6]:
resize=cv2.resize(a,(int(a.shape[1]/3),int(a.shape[0]/3)))
cv2.imshow("img",a)


# Factors of a number

In [4]:
import math

In [139]:
a=36
a

36

In [141]:
math.gcd(50,10)

10

In [13]:
def factors(number):
    b=[]
    for i in range(2,int(number/2+1)):
        if number%i==0:
            b.append(i)
    return b

In [16]:
factors(12)

[2, 3, 4, 6]

In [18]:
int(2.5)

2

# LCM and HCF of two numbers

In [135]:
def compute_LCM(x,y):
    if x>y:
        greater=x
    else:
        greater=y
    while(True):
        if greater%x==0 and greater%y==0:
            lcm=greater
            break
        greater+=1
    return lcm

print("The L.C.M is",compute_LCM(50,10))

The L.C.M is 50


In [150]:
def compute_hcf(x,y):
    while(y):
        x,y=y,x%y
    return x
hcf=compute_hcf(10,50)
print("The HCF is ",hcf)


The HCF is  10


In [5]:
def LCM(x,y):
    if x>y:
        greater=x
    else:
        greater=y
    
    while(True):
        if greater%x==0 and greater%y==0:
            lcm=greater
            break
        greater+=1
    return lcm

In [6]:
LCM(20,30)

60

In [4]:
result=[[0,0,0],
        [0,0,0],
        [0,0,0]]
a=[[1,2,3],
   [3,4,5],
   [5,6,7]]
for i in range(len(a)):
    for j in range(len(a[0])):
        result[i][j]=a[j][i]
result

[[1, 3, 5], [2, 4, 6], [3, 5, 7]]

In [5]:
a=[[1,2,3],
   [3,4,5],
   [5,6,7]]
b=[[3,4,8],
   [1,2,7],
   [5,9,5]]
result=[[0,0,0],
        [0,0,0],
        [0,0,0]]

In [26]:
result=[[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            result[i][j]+=a[i][k]*b[k][j]
result

[[20, 35, 37], [38, 65, 77], [56, 95, 117]]

In [23]:
result=[[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            result[i][j]+=a[i][k]*b[k][j]
result

[[20, 35, 37], [38, 65, 77], [56, 95, 117]]

In [33]:
a=0
b=0
for i in range(7):
    a=+i
    b=b+i
    print(a,b)
    

0 0
1 1
2 3
3 6
4 10
5 15
6 21


In [ ]:
wmwmwmwwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmmwmwmwmwmwmwmwmwwmwmwmwmwmwmwwmwmwmwmwmwmwmwmwmwmwmwmwmwmw

In [75]:
a=[]
num1=2
num2=2
for i in range(num1):
    
    for j in range(num2):
        a.append(0)
a

[0, 0, 0, 0]

# Patterns

In [24]:
a=5
for i in range(a):
    print((a-i)*"* ")
        
    

* * * * * 
* * * * 
* * * 
* * 
* 


In [27]:
a=5
for i in range(a+1):
    print(i*"* ")


* 
* * 
* * * 
* * * * 
* * * * * 


In [39]:
for i in range(a):
    print((a-i)*"  ","*")
    print((i+1)*"  ","*")
        

           *
   *
         *
     *
       *
       *
     *
         *
   *
           *


In [47]:
a=5
for i in range(a):
    print((a-i)*" ",(i+1)*" *")
    

       *
      * *
     * * *
    * * * *
   * * * * *


In [56]:
a=5
for i in range(a):
    print(i*" ",(a-i)*"* ")

 * * * * * 
  * * * * 
   * * * 
    * * 
     * 


In [8]:
a=np.empty(None,int)
a

array(897988541)

In [11]:
a=5*[None]
a

[None, None, None, None, None]

# Permutation and Combination

In [66]:
from itertools import permutations
for i in range(1,4):
    perm=permutations([1,2,3],i)
    for i in list(perm):
        print(i)

(1,)
(2,)
(3,)
(1, 2)
(1, 3)
(2, 1)
(2, 3)
(3, 1)
(3, 2)
(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


In [69]:
from itertools import combinations
for i in range(1,4):
    comb=combinations([1,2,3],i)
    for i in list(comb):
        print(i)

(1,)
(2,)
(3,)
(1, 2)
(1, 3)
(2, 3)
(1, 2, 3)


In [25]:
array=[1,2,3,4,5]
k=2
subarray=[]
maximum=[]
minimum=[]
for i in range(len(array)):
    for j in range(i,k):
        print(array[j])


1
2
2


In [45]:
array=[1,2,3,4,5]
k=3
subarray=[]
maximum=[]
minimum=[]
for i in range(len(array)):
    for j in range(i,k):
        print(array[j])
from itertools import combinations
comb=combinations(array,4)
arr=[]
for i in comb:
    arr.append(i)
maximum=[]
minimun=[]
for i in arr:
    maximum.append(max(i))
    minimum.append(min(i))
set(maximum),set(minimum)
        
         

1
2
3
2
3
3


({4, 5}, {1, 2})

In [ ]:
for i in subarray:
    
    maximum.append(max(i))
    minimum.append(min(i))
maximum,minimum

In [8]:
max_min([1,2,3,4,5],2)

(1, 2)
(1, 3)
(1, 4)
(1, 5)
(2, 3)
(2, 4)
(2, 5)
(3, 4)
(3, 5)
(4, 5)


([], [])

# Find all of the integer array which sum is equal to a number

In [11]:
from itertools import combinations 
a=[1,2,3,4,5,4,3,2,6,7]
num=10
b=[]
for i in range(len(a)):
    comb=combinations(a,i)
    for j in comb:
        if sum(j)==10:
            b.append(j)
print(set(b))
            
        
        
        
        

{(1, 5, 4), (3, 7), (4, 6), (1, 2, 3, 4), (1, 2, 4, 3), (1, 3, 6), (1, 4, 5), (5, 3, 2), (3, 5, 2), (2, 5, 3), (1, 2, 7), (3, 4, 3), (1, 3, 4, 2), (2, 3, 5), (2, 4, 4), (2, 3, 3, 2), (2, 2, 6), (4, 4, 2), (1, 4, 3, 2), (1, 2, 5, 2)}


In [18]:
a=[1,2,3,4,-1,-3,-2,-1]
b=[]
c=[]
d=[]
for i in a:
    if i>1:
        b.append(i)
    if i<1:
        c.append(i)
for i,j in zip(range(len(b)),range(len(c))):
    d.append(b[i])
    d.append(c[j])
b,c,d

([2, 3, 4], [-1, -3, -2, -1], [2, -1, 3, -3, 4, -2])

# The Minion Game

In [7]:
from itertools import combinations
len("string")
string.ucase()

AttributeError: 'str' object has no attribute 'ucase'

In [20]:
string="Banana"
vowels=["A","E","I","O","U"]
for i in range(1,len(string)):
    comb=combinations(string.upper(),i)
    for j in comb:
        for k in vowels:
            if j=="A":
                print("Stuart")
            else:
                print("Kevin")
        

Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevin
Kevi

In [ ]:
def Minion_game(string):
    

In [15]:
a=["a","e","i"]
a.upper()

AttributeError: 'list' object has no attribute 'upper'

# Move all negative numbers to beginning and positive to end with constant extra space

In [29]:
a=[1,2,3,-2,-5,1,-4,-3,4,3,6,-3,6,-2,7,8,-3]
result=[]
for i in range(len(a)):
    if a[i]<0:
        result.append(str(a[i]))
for i in range(len(a)):
    if a[i]>0:
        result.append(str(a[i]))
        
result=" ".join(result)
result
        
        

'-2 -5 -4 -3 -3 -2 -3 1 2 3 1 4 3 6 6 7 8'

In [35]:
a="abcde"
r=list(reversed(a))
r="".join(r)
r

'edcba'

# Union of two array

In [58]:
a=[1,2,3,4]
b=[4,5,6,3]
a+b


[1, 2, 3, 4, 4, 5, 6, 3]

In [59]:
r=[]
for i,j in zip(a,b):
    r.append(i)
    r.append(j)
    

In [61]:
r

[1, 4, 2, 5, 3, 6, 4, 3]

In [62]:
duplicate=[]
for i in r:
    for j in range(i+1,len(r)):
        if r[i]==r[j]:
            duplicate.append(r[i])
duplicate

[4, 3, 3]

In [63]:
duplicate=set(duplicate)
for i in duplicate:
    r.remove(i)

In [65]:
print(len(r))

6


In [68]:
r.insert(0,9)
r

[9, 1, 2, 5, 6, 4, 3, 0, 0]

In [69]:
a=[1,2,3,4]
b=a.pop()
a

[1, 2, 3]

# Given an array arr of N integers. Find the contiguous sub-array with maximum sum

In [7]:
def sub_array(a): 
    max_so_far = a[0]
    max_ending_here = 0
     
    for i in range(0, len(a)):
        max_ending_here = max_ending_here + a[i]
        if max_ending_here < 0:
            max_ending_here = 0
         
        # Do not compare for all elements. Compare only  
        # when  max_ending_here > 0
        elif (max_so_far < max_ending_here):
            max_so_far = max_ending_here
             
    return max_so_far

In [23]:
a=[1,3,-1,4,5,2,-2,4,5,6,3,-5,3,-9]
sums=[]
from itertools import combinations
for i in range(1,len(a)):
    comb=combinations(a,i)
    for j in comb:
        sums.append(sum(j))
max(sums)

36

In [ ]:
def maxSubArraySum(a,size):
      
    max_so_far = max(a) - 1
    max_ending_here = 0
      
    for i in range(0, size):
        max_ending_here = max_ending_here + a[i]
        if (max_so_far < max_ending_here):
            max_so_far = max_ending_here
 
        if max_ending_here < 0:
            max_ending_here = 0  
    return max_so_far
  
# Driver function to check the above function
a = [-13, -3, -25, -20, -3, -16, -23, 12, -5, 10, -15, -4, -7]
print("Maximum contiguous sum is", maxSubArraySum(a,len(a)))
  
    

# Rough

In [47]:
class Test:
    def __init__(self, name):
        self.cards = []
        self.name = name
    def __str__(self):
        return '{} holds ...'.format(self.name)

obj1 = Test('obj1')
print(obj1)
obj2 = Test('obj2')
print(obj2)

obj1 holds ...
obj2 holds ...


In [50]:
isinstance(obj1,Test)

True

In [77]:
def fast(items=[]):
    items.append(1)
    return items
print(fast())
print(fast())

[1]
[1, 1]


In [85]:
a=[1,2,1,2,3,4,56,4,32,1,3,4,5,2]
set(a)


{1, 2, 3, 4, 5, 32, 56}

In [91]:
def dic(words):
    wordList = {}
    for index in words:
        try:
            wordList[index] += 1
        except KeyError:
            wordList[index] = 1
    return wordList
wordList='1,3,2,4,5,3,2,1,4,3,2'.split(',')
print(wordList)
print(dic(wordList))

['1', '3', '2', '4', '5', '3', '2', '1', '4', '3', '2']
{'1': 2, '3': 3, '2': 3, '4': 2, '5': 1}


In [10]:
class Test():
    def __init__(self):
        self.x=1
        self.y="hello this is the main class"
    
t=Test()
print(t.x)
print(t.x)  
print(t.y)
    

1
1
hello this is the main class


In [11]:
class Test1():
    def __init__(self):
        self.x="Hello My name is Ashish"
        
    def hello(self):
        print("Good to go")
class Test2(Test1):
    def __init__(self):
        self.y="Hi this is subclass"

In [12]:
obj1=Test2()
obj1.hello()

Good to go


# No of Jumps

In [44]:
def maxSumIS(arr):
    jump=int()
    l=len(arr)
    a=0
    for i in range(len(arr)):
        a=a+arr[a]
        if a>=len(arr):
            jump=i+1
            break
    print(jump)
    
maxSumIS([1,4,4,6,7,6,5,3,4,5,0,2,4,1,2,2])

6


# Max Product Sub-array

In [52]:
def max_product(arr):
    result=arr[0]
    for i in range(len(arr)):
        mul=arr[i]
        for j in range(i+1,len(arr)):
            result=max(result,mul)
            mul*=arr[j]
            
        result=max(result,mul)
    return result
#complete the following

In [53]:
max_product([1,2,3,2])

12

## Trapping Rainwater

In [5]:
arr=[6,9,9]
res=0
n=3
for i in range(1,n-1):
    left=arr[i]
    for j in range(i):
        left=max(left,arr[j])

    right=arr[i]
    for j in range(i+1,n):
        right=max(right,arr[j])

    res = res + (min(left, right) - arr[i])
print(res)

0


In [27]:
arr=[3,0,0,2,0,4]
n=6
left=[0]*n
right=[0]*n
left[0]=arr[0]
for i in range(1,n):
    left[i]=max(left[i-1],arr[i])
right[n-1]=arr[n-1]
for i in range(n-2,-1,-1):
    right[i]=max(right[i+1],arr[i])


In [30]:
n=6
arr=[3,0,0,2,0,4]
left=[0]*n
right=[0]*n
left[0] = arr[0]
water=0
for i in range( 1, n):
    left[i] = max(left[i-1], arr[i])

# Fill right array
right[n-1] = arr[n-1]
for i in range(n-2, -1, -1):
    right[i] = max(right[i + 1], arr[i]);

# Calculate the accumulated water element by element
# consider the amount of water on i'th bar, the
# amount of water accumulated on this particular
# bar will be equal to min(left[i], right[i]) - arr[i] .
for i in range(0, n):
    water += min(left[i], right[i]) - arr[i]
water

10