# Using Supervised Learning

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews=["nice food",
        "amazing resturant",
         "too good",
         "just love it",
         "will go again",
         "horrible food",
         "will never go there",
         "poor service",
         "poor quality",
         "needs improvement"]

sentiment=np.array([1,1,1,1,1,0,0,0,0,0])

In [8]:
one_hot("amazing restaurant",30)

[11, 4]

In [10]:
vocab_size=30
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]
print(encoded_reviews)

[[17, 3], [11, 24], [6, 8], [2, 3, 17], [8, 10, 22], [29, 3], [8, 19, 10, 7], [22, 1], [22, 25], [23, 22]]


In [12]:
max_length=4
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding="post")
padded_reviews

array([[17,  3,  0,  0],
       [11, 24,  0,  0],
       [ 6,  8,  0,  0],
       [ 2,  3, 17,  0],
       [ 8, 10, 22,  0],
       [29,  3,  0,  0],
       [ 8, 19, 10,  7],
       [22,  1,  0,  0],
       [22, 25,  0,  0],
       [23, 22,  0,  0]])

In [13]:
max_length=3
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding="post")
padded_reviews

array([[17,  3,  0],
       [11, 24,  0],
       [ 6,  8,  0],
       [ 2,  3, 17],
       [ 8, 10, 22],
       [29,  3,  0],
       [19, 10,  7],
       [22,  1,  0],
       [22, 25,  0],
       [23, 22,  0]])

In [17]:
embeded_vector_size=4
model=Sequential()
model.add(Embedding(vocab_size,embeded_vector_size,input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1,activation="sigmoid"))

In [18]:
x=padded_reviews
y=sentiment

In [19]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 4)              120       
_________________________________________________________________
flatten_1 (Flatten)          (None, 12)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 13        
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.fit(x,y,epochs=100,verbose=0)

In [24]:
loss,accuracy=model.evaluate(x,y)
accuracy

1/1 [==============================] - 0s 2ms/step - loss: 0.4856 - accuracy: 1.0000


1.0

In [27]:
weights=model.get_layer("embedding").get_weights()[0]
len(weights)

30

In [28]:
weights[11]

array([-0.11497031, -0.20267138, -0.16653013, -0.13105898], dtype=float32)

In [29]:
weights[3]

array([0.1020871 , 0.10280099, 0.09432071, 0.17034444], dtype=float32)